### PR TITLE
Fix broken design 

### PR DESCRIPTION
**Pull request by khatabwedaa**
Hi @wobsoriano, your work is awesome man I fix some design issues, I hope you will like it and also edit some stuff in UI Elements Page

### CODE REVIEW

**Comment by wobsoriano** [comment]
Hi thanks will check this

**Comment by wobsoriano** [comment]
Getting this in the preview: `/views/UIElements.vue(139,24): error TS2304: Cannot find name 'email'.`

**Comment by khatabwedaa** [comment]
@wobsoriano  Fixed !🤘

**Comment by khatabwedaa** [comment]
@wobsoriano 👀

**Comment by wobsoriano** [comment]
> @wobsoriano 👀

Still reviewing, might still need other buttons there tho

**Comment by khatabwedaa** [comment]
> > @wobsoriano eyes
> 
> Still reviewing, might still need other buttons there tho

Where

**Comment by wobsoriano** [comment]
Merged. Thanks!

**Pull request merged**
